controller_list:
  - name: fake_Arm_controller
    joints:
      - arm_shoulder_pan_joint
      - arm_shoulder_lift_joint
      - arm_elbow_flex_joint
      - arm_wrist_flex_joint
  - name: fake_Gripper_controller
    joints:
      - gripper_joint
      - gripper_link_joint